Signing the jar file
keytool -genkeypair -alias mykey -keyalg RSA -keysize 2048 -validity 365 -keystore myKeystore.jks
jarsigner -keystore myKeystore.jks -storepass umesh1997 Project1-0.0.1-SNAPSHOT.jar mykey
jarsigner -verify Project1-0.0.1-SNAPSHOT.jar 
